package com.entites;


// Generated 1 janv. 2019 19:11:57 by Hibernate Tools 4.3.1



/**
 * Contact generated by hbm2java
 */
public class Contact  implements java.io.Serializable {


     private String fullName;
     private String sujet;
     private String email;
     private String message;

    public Contact() {
    }

    public Contact(String fullName, String sujet, String email, String message) {
       this.fullName = fullName;
       this.sujet = sujet;
       this.email = email;
       this.message = message;
    }
   
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getSujet() {
        return this.sujet;
    }
    
    public void setSujet(String sujet) {
        this.sujet = sujet;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }




}


