package com.entites;



// Generated 1 janv. 2019 19:11:57 by Hibernate Tools 4.3.1



/**
 * Papier generated by hbm2java
 */
public class Papier  implements java.io.Serializable {


     private Integer id;
     private String title;
     private String file;

    public Papier() {
    }

    public Papier(String title, String file) {
       this.title = title;
       this.file = file;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getFile() {
        return this.file;
    }
    
    public void setFile(String file) {
        this.file = file;
    }




}


