package com.entites;
// Generated 1 janv. 2019 19:11:57 by Hibernate Tools 4.3.1



/**
 * Participant generated by hbm2java
 */
public class Participant  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String lastName;
     private String email;
     private String phoneNumber;
     private String adress;
     private String username;
     private String password;
     private String typeParti;

    public Participant() {
    }

    public Participant(String name, String lastName, String email, String phoneNumber, String adress, String username, String password, String typeParti) {
       this.name = name;
       this.lastName = lastName;
       this.email = email;
       this.phoneNumber = phoneNumber;
       this.adress = adress;
       this.username = username;
       this.password = password;
       this.typeParti = typeParti;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getAdress() {
        return this.adress;
    }
    
    public void setAdress(String adress) {
        this.adress = adress;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getTypeParti() {
        return this.typeParti;
    }
    
    public void setTypeParti(String typeParti) {
        this.typeParti = typeParti;
    }




}


